-- decision_events RLS policies
-- Fixes 401 / 42501 errors when client inserts decision rows.

-- Ensure runtime roles can access the table (RLS still applies).
GRANT SELECT, INSERT ON TABLE public.decision_events
  TO anon, authenticated, service_role;

-- Ensure sequence access for inserts when id is generated by a sequence.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
  TO anon, authenticated, service_role;

ALTER TABLE public.decision_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS decision_events_select_all ON public.decision_events;
CREATE POLICY decision_events_select_all
ON public.decision_events
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS decision_events_insert_client ON public.decision_events;
CREATE POLICY decision_events_insert_client
ON public.decision_events
FOR INSERT
TO anon, authenticated
WITH CHECK (
  session_id IS NOT NULL
  AND thought_id IN ('dictator', 'volunteer', 'exchange', 'trust')
);

NOTIFY pgrst, 'reload schema';
